### PR TITLE
Fix: Adds support for Visua11y's 'no animations' option (fixes #4)

### LINKED ISSUE #4: Visua11y no animation support
When Visua11y [_noAnimations](https://github.com/cgkineo/adapt-visua11y/blob/db8cfc126f8b01f9c6d72ea34aa73832addcb877/example.json#L55) is enabled, stop video and show end frame.

Same as https://github.com/cgkineo/adapt-graphicLottie/issues/3

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #4 

### Fix
* Adds support for Visua11y's "no animations" option. Requires framework **v5.31.27** due to the DOM Element Modification API dependency
* Added a real world example to _example.json_

### Notes
Although the original ticket requested that the video stop on the _end_ frame, I felt it might be safer if we stop on the _first_ frame in case the video was large and hadn't fully loaded.

Alternatively, we could add support for a poster image and show that instead. I'm not sure how complicated that would get, though.

### CODE REVIEW

File: js/VideoView.js [hunk 1]
```diff
@@ -30,6 +32,7 @@ export default class VideoView extends Backbone.View {
   setUpListeners() {
     this.$el.on('onscreen', this.onScreenChange);
     this.listenTo(Adapt, 'device:resize', this.render);
+    documentModifications.on('changed:html', this.checkVisua11y);
```
Comment (oliverfoster) [inline js/VideoView.js]: Sorry, I just remembered that `documentModifications` is a Backbone.Events interface.

```suggestion
    this.listenTo(documentModifications, 'changed:html', this.checkVisua11y);
```

File: js/VideoView.js [hunk 2]
```diff
@@ -11,7 +13,7 @@ export default class VideoView extends Backbone.View {
   }
 
   initialize() {
-    _.bindAll(this, 'render', 'onScreenChange', 'update', 'onDataReady');
+    _.bindAll(this, 'render', 'onScreenChange', 'update', 'onDataReady', 'checkVisua11y');
```
Comment (oliverfoster) [inline js/VideoView.js]:
```suggestion
    _.bindAll(this, 'render', 'onScreenChange', 'update', 'onDataReady');
```

**Comment by swashbuck** [comment]
I think this is ready for testing again. I had some issues around checking "no animations" on one page, then unchecking it on another and returning.

File: js/VideoView.js [hunk 3]
```diff
@@ -88,10 +110,27 @@ export default class VideoView extends Backbone.View {
...
+    this.config._loops = this.config._originalLoops;
+    this.config._autoPlay = this.config._originalAutoPlay;
+    this.play();
+  }
+
   update() {
     this.$player.toggleClass('is-graphicvideo-playing', !this.video.paused);
     this.$player.toggleClass('is-graphicvideo-paused', this.video.paused);
-    Adapt.a11y.toggleEnabled(this.$player.find('.graphicvideo__rewind'), this.video.currentTime !== 0);
+    a11y.toggleEnabled(this.$player.find('.graphicvideo__rewind'), this.video.currentTime !== 0);
```
Comment (oliverfoster) [inline js/VideoView.js]:
```suggestion
    const isNotAtStart = (this.video.currentTime !== 0);
    a11y.toggleEnabled(this.$player.find('.graphicvideo__rewind'), isNotAtStart);
```

**Review by oliverfoster — APPROVED** [review]
